config/routes.rb
# Route prefixes use a single letter to allow for vanity urls of two or more characters
Rails.application.routes.draw do
  if defined? Sidekiq
    require 'sidekiq/web'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web, at: '/admin/sidekiq/jobs', as: :sidekiq
    end
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin' if defined? RailsAdmin

  # Static pages
  match '/error' => 'pages#error', via: [:get, :post], as: 'error_page'
  get '/terms' => 'pages#terms', as: 'terms'
  get '/privacy' => 'pages#privacy', as: 'privacy'

  # OAuth
  oauth_prefix = Rails.application.config.auth.omniauth.path_prefix
  get "#{oauth_prefix}/:provider/callback" => 'users/oauth#create'
  get "#{oauth_prefix}/failure" => 'users/oauth#failure'
  get "#{oauth_prefix}/:provider" => 'users/oauth#passthru', as: 'provider_auth'
  get oauth_prefix => redirect("#{oauth_prefix}/login")

  # Devise
  devise_prefix = Rails.application.config.auth.devise.path_prefix

  # hack for blocking registration
  get "#{devise_prefix}/signup" => redirect('404')

  devise_for :users, path: devise_prefix,
             controllers: {registrations: 'users/registrations',
                           sessions: 'users/sessions',
                           passwords: 'users/passwords',
                           confirmations: 'users/confirmations',
                           unlocks: 'users/unlocks',
                           :invitations => 'users/invitations'},
             path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}

  devise_scope :user do
    get "#{devise_prefix}/after" => 'users/registrations#after_auth', as: 'user_root'
    root 'users/sessions#new'
  end

  get devise_prefix => redirect('/a/signup')

  # User
  resources :users, path: 'u', only: [:show, :index, :new, :edit, :update, :create, :destroy] do
    collection do
      get :login_as
      get :new_technician
      get :technicians
      get :service_advisors

      post :create_technician
    end

    member do
      post :login

      delete :destroy
    end

    resources :authentications, path: 'accounts'
  end

  resources :dealerships, except: :show
  resources :inventories, only: [:create]

  get '/home' => 'users#show', as: 'user_home'

  # Dummy preview pages for testing.
  get '/p/test' => 'pages#test', as: 'test'
  get '/p/email' => 'pages#email' if ENV['ALLOW_EMAIL_PREVIEW'].present?

  get 'robots.:format' => 'robots#index'

  resources :vehicle_report_cards, path: 'reports' do
    resources :next_maintenance_appointments
    resources :scheduled_maintenance_items
    resources :fluid_levels
    resources :wiper_blades
    resources :vehicle_components
    resources :tire_wear_indicates
    resources :brake_wear_indicates
    member do
      get :send_pdf
      get :email_pdf
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  def new
    self.resource = (current_user or resource_class.new)
  end

  def create
    if user_signed_in?
      Devise.paranoid = false
      params[resource_name] ||= {}
      params[resource_name][:email] = current_user.email
    end
    super
  end

  protected

  def after_resending_confirmation_instructions_path_for(resource_name)
    user_signed_in? and edit_user_registration_path or super
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  protected

end

app/controllers/users/oauth_controller.rb
# Manage OAuth flows
# OauthController handles the business logic for OmniAuth

require 'addressable/uri'

class Users::OauthController < ApplicationController
  class AuthError < Exception;
  end

  skip_authorization_check
  protect_from_forgery except: [:create]
  skip_before_action :authenticate_user!
  before_action :set_vars

  # OmniAuth passthru to use for route naming
  def passthru
    render :nothing, status: 404
  end

  # OAuth Callback
  def create
    # Uncomment to debug oauth response
    # return render partial: 'authentications/debug_omniauth'

    @auth = Authentication.unscoped.find_by_provider_and_proid(@provider, @omniauth['uid'])

    # Check for possible orphaned authentication record
    if @auth && @auth.user.blank?
      @auth.destroy
      @auth = nil
    end

    # Update auth with latest data
    @auth.update_from_omniauth(@omniauth) if @auth

    # make sure session is cleared from any previous requests
    session.delete(:omniauth)
    session.delete(:cached_auth_for_display)

    # Account Merge
    # Auth credentials exist and user is logged in.
    # Typical action is to prompt user to merge or switch accounts.
    if @auth && user_signed_in? && @auth.user != current_user
      set_cached_user_for_prompt
      @flow = :merge
      redirect_to new_user_merge_path(current_user)

      # Login
      # Auth credentials exist and user is not logged in
    elsif @auth && (@flow == :login || @flow == :signup)
      @flow = :login
      sign_in @auth.user
      redirect_to @origin

      # Reconnecting Existing Account
      # Auth exists and user is not in login or signup flow.
      # Used after prompting user to reimport data from a provider.
      # Typical action is to return user to origin; probably connect accounts page.
    elsif @auth
      flash[:notice] = I18n.t 'accounts.updated'
      redirect_to @origin

      # Connecting New Account
      # Auth credentials are new and the user is logged in.
    elsif user_signed_in?
      @auth = Authentication.build_from_omniauth(@omniauth)
      @auth.user = current_user
      @auth.save!
      flash[:notice] = I18n.t 'accounts.connected'
      redirect_to @origin

      # Sign-up
      # Auth credentials are new and the user is not logged in
    else
      session[:omniauth] = @omniauth
      # Do not log user in yet, redirect to after_auth so user
      # can fill in any additional registration requirements like email
      redirect_to default_redirect_path
    end

  rescue => e
    report_omniauth_error(e)
    raise
  end

  def failure
    report_omniauth_error(AuthError.new(params[:message]))
    url = case @flow
            when :login
              new_user_session_path(failed: params[:message], provider: @provider)
            when :signup
              new_user_registration_path(failed: params[:message], provider: @provider)
            when :connect
              authentications_route(failed: params[:message], provider: @provider)
          end
    if url
      redirect_to url
    else
      render 'authentications/failure'
    end
  end

  protected

  def authentications_route(*args)
    (user_signed_in? ? user_authentications_path(current_user, *args) : nil)
  end

  def default_redirect_path
    user_root_path flow: @flow
  end

  def set_vars
    @omniauth = request.env['omniauth.auth'] || {}
    @origin = request.env['omniauth.origin'].to_s.presence || params[:origin]
    uri = Addressable::URI.parse(@origin)
    path = uri && uri.path.presence

    # Override origin url if home, sign up, or login pages
    @origin = default_redirect_path unless valid_after_sign_in_path?(path)

    flow = request.env['omniauth.params'].try(:[], 'flow') || params['flow']
    @flow = flow.present? && flow.to_sym || nil
    @provider = @omniauth && @omniauth[:provider] || session && session[:oauth] && session[:oauth].first.first
    @provider = @provider.downcase if @provider.is_a?(String)
  end

  def set_cached_user_for_prompt
    cached_user_for_prompt({
                               auth_id: @auth && @auth.id || nil,
                               image_url: @omniauth[:info][:image],
                               name: @omniauth[:info][:name] || @omniauth[:info][:first_name],
                               provider: @omniauth[:provider].downcase,
                           })
  end

  # https://github.com/intridea/omniauth/issues/185
  # TODO: remove this if no longer needed; write tests first
  def handle_unverified_request
    true
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  prepend_before_action :force_logout, only: :edit

  protected

  # logout since devise will redirect to user home for logged in user instead of allowing them to edit password
  def force_logout
    sign_out(resource) if user_signed_in?
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include DeviseReturnToConcern

  before_action :set_vars
  before_action :permit_params, only: [:create, :update]
  after_action :cleanup_oauth, only: [:create, :update]

  # Additional resource fields to permit
  # Devise already permits email, password, etc.
  SANITIZED_PARAMS = [:first_name, :last_name].freeze

  # GET /resource/sign_up
  def new
    check_for_existing_account
    super
  end

  # GET /resource/after
  # Redirect user here after login or signup action
  # Used to require additional info from the user like email address, agree to new TOS, etc.
  def after_auth
    # User should be already signed in by Devise
    # or in process of signing up via OAuth provider
    if signed_in?
      authenticate_scope!
    else
      build_resource({})
    end

    # Check if anything went wrong with OAuth
    # User will already be signed in if using username/password sign up
    if !signed_in? && @auth.blank?
      redirect_to root_path

      # Check if resource is valid
      # Resource will not yet be saved if user is signing up with OAuth
    elsif resource.persisted? && resource.valid?
      path = after_sign_in_path_for(current_user)
      path = user_home_path unless valid_after_sign_in_path?(path)
      redirect_to path

      # Redisplay registration form with OAuth data for user to confirm
    else
      check_for_existing_account
      redirect_to after_sign_in_path_for(current_user)
    end
  end

  # POST /resource
  def create
    check_for_existing_account
    super
    @auth.save! if @auth.present? && resource.persisted?
  rescue ActiveRecord::ActiveRecordError => e
    resource.destroy
    sign_out(resource) if signed_in?
    report_error(e)
    flash.clear
    flash[:error] = I18n.t 'errors.unknown'
    redirect_to error_page_path
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def delete
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  def permit_params
    devise_parameter_sanitizer.for(:sign_up) << SANITIZED_PARAMS
    devise_parameter_sanitizer.for(:account_update) << SANITIZED_PARAMS
  end

  def build_resource(*args)
    super
    if session[:omniauth].present?
      @auth ||= Authentication.build_from_omniauth(session[:omniauth])
      resource.authentications << @auth
      @auth.populate_names
      resource.reverse_merge_attributes_from_auth(@auth)
    end
    resource
  end

  # Override Devise method to disable current_password requirement
  def update_resource(resource, params)
    if resource.password_required?
      super
    else
      if params[:password].blank?
        params.delete(:password)
        params.delete(:password_confirmation)
      end
      result = resource.update(params)
      clean_up_passwords resource
      result
    end
  end

  # Clear out omniauth session to prevent session bloat
  def cleanup_oauth
    session.delete(:omniauth) if resource.persisted?
  end

  def after_sign_up_path_for(resource)
    user_root_path
  end

  def check_for_existing_account
    @existing_account = false
    email = (resource.try(:email) or params[:user].try(:[], :email))
    if email.blank? and session[:omniauth].present?
      @auth = Authentication.build_from_omniauth(session[:omniauth])
      email = @auth.oauth_data[:email]
    end
    @existing_account = User.find_by_email(email.strip.downcase) if email
  end

  def set_vars
    @failed = params[:failed]
    @provider = params[:provider]
    @auth = nil
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include DeviseReturnToConcern
  prepend_before_filter :force_reset_session, only: :destroy

  def new
    @failed = params[:failed]
    @provider = params[:provider]
    return render 'failed' if @failed
    super
  end

  def force_reset_session
    reset_session
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::PasswordsController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @users = User.order('users.created_at desc').page(params[:page])
    @users = @users.where({dealership_id: current_dealership.id}) if !current_user.admin?
  end

  def show
    redirect_to root_path, notice: flash[:notice], error: flash[:error]
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_url, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user.technician? ? technicians_users_path : users_url, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # def new_technician
  #   @user = User.new
  # end
  #
  # def create_technician
  #   @user = User.new(user_params)
  #   if @user.save
  #     redirect_to technicians_users_path, notice: "Technician created successfully."
  #   else
  #     render 'new_technician'
  #   end
  # end
  #
  # def technicians
  #   @users = if current_user.admin?
  #              User.technician
  #            elsif current_user.dealership_id?
  #              current_user.dealership.users.technicians
  #            else
  #              User.none
  #            end.order('users.created_at desc').page(params[:page])
  # end
  #
  # def service_advisors
  #   @users = current_user.dealership.users.service_advisor
  # end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to users_url, notice: 'User was successfully destroyed.'
    else
      redirect_to users_url, notice: 'Error while destroying a user.'
    end
  end

  def login_as
    @service_advisors = current_user.dealership.users.service_advisor
    @technicians = current_user.dealership.users.technician
  end

  def login
    @user = User.find(params[:id])
    sign_in(:user, @user)
    redirect_to after_sign_in_path_for(@user), notice: "You are currently logged in as #{@user.role.humanize.downcase} #{@user.name_or_email_or_username}"
  end

  private
  def user_params
    if params[:user] && params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    params.require(:user).permit(:username, :password, :password_confirmation, :first_name, :last_name, :email, :role, :dealership_id)
  end
end

app/views/users/_avatar.html.haml
- size ||= :tiny
- alt ||= ''
- user ||= current_user
.avatar{class: size.to_s}
  = image_tag user.image_url(size: size, ssl: request.ssl?), alt: alt
  %i.default.glyphicon.glyphicon-user

app/views/users/_card.html.haml
- user ||= User.new
- size ||= :thumb
- target ||= '_self'
- username ||= 'view'
- profile_url = user_path(user) unless defined? profile_url

.card__user{class: "card__user-#{size}"}
  = render 'users/avatar', user: user, size: size
  %h4= user.name
  .card__user__links
    - if profile_url
      = link_to username, profile_url, target: target

  = yield

app/views/users/_form.html.haml
= form_for(@user) do |f|
  .form-group
    = render 'active_record_errors', object: @user
  .form-group
    = f.label :email
    = f.email_field :email, placeholder: 'eg: jhon@example.com', class: 'form-control'
  .form-group
    = f.label :username
    = f.text_field :username, placeholder: 'eg: jhonsmith', class: 'form-control'
  .form-group
    = f.label :first_name
    = f.text_field :first_name, placeholder: 'eg: Jhon', class: 'form-control'
  .form-group
    = f.label :last_name
    = f.text_field :last_name, placeholder: 'eg: Smith', class: 'form-control'
  .form-group
    = f.label :role
    = f.select :role, current_user.roles_for_select_box, {prompt: true}, class: 'form-control'
  = render 'dealership_field', f: f
  .form-group
    = f.label :password
    = f.password_field :password, class: 'form-control'
    - if !@user.new_record?
      .help-block
        Leave blank if you don't wish to change password.
  .form-actions
    = f.button :submit, class: 'btn btn-primary btn-lg'
    = link_to 'cancel', dealerships_path, class: 'btn btn-default btn-lg mL10'

app/views/users/_user.html.haml
%tr
  %td= user.email.presence || '-'
  %td= user.username.presence || '-'
  %td= user.role.presence || '-'
  %td= user.dealership.try(&:title) || '-'
  %td= l(user.created_at, format: :short)
  %td
    = link_to 'Edit', edit_user_path(user), class: 'btn btn-default btn-xs'
    = link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-default btn-xs'

app/views/users/_users.html.haml
- if users.present?
  .table-responsive
    %table.table.table-striped.table-hover.table-bordered
      %thead
        %tr
          %th Email
          %th Username
          %th Role
          %th Dealership
          %th{width: '20%'} Created At
          %th{width: '15%'}

      %tbody
        = render users
  = paginate users
- else
  .row
    .col-md-12.text-center
      Nothing to display

app/views/users/edit.html.haml
= render 'form'

app/views/users/index.html.haml
.row.mB20
  .col-xs-12
    = link_to 'New User', new_user_path, class: 'btn btn-primary btn-lg pull-right mB20'
= render 'users', users: @users
%br

app/views/users/login_as.html.haml
.row
  .col-xs-12
    %p.text-muted
      Choose your account and click on login button to proceed.
.row
  .col-xs-12.col-sm-6
    = panel context: 'primary' do
      .panel-heading
        %strong
          = t('users.roles.service_advisor').pluralize
      .panel-body
        = render 'users/login_as/users', users: @service_advisors
  .col-xs-12.col-sm-6
    = panel context: 'primary' do
      .panel-heading
        %strong
          = t('users.roles.technician').pluralize
      .panel-body
        = render 'users/login_as/users', users: @technicians

app/views/users/new.html.haml
= render 'form'

app/views/users/new_technician.html.haml
= panel do
  .panel-body
    = form_for @user, url: create_technician_users_path do |f|
      = render 'application/active_record_errors', object: @user
      .form-group
        %lable Username:
        = f.text_field :username, autocomplete: :off, autofocus: true, required: true, placeholder: "eg: jhonsmith", class: 'form-control input-lg'
        .help-block
          Spaces and special characters not allowed.
      .form-group
        %lable Password:
        = f.password_field :password, autocomplete: :off, required: true, minlength: 8, class: 'form-control input-lg'
        .help-block
          Minimum 8 characters.
      = render 'application/dealership_field', f: f
      = f.hidden_field :role, value: 'technician'
      %button.btn.btn-primary.btn-lg{:type => "submit"} Create Technician
      = link_to 'Cancel', technicians_users_path, class: 'btn btn-default btn-lg'

app/views/users/service_advisors.html.haml
- if @users.present?
  .table-responsive
    %table.table.table-striped.table-bordered
      %tr
        %th
          E-mail
        %th
      - @users.each do |user|
        %tr
          %td
            = user.email
          %td.text-center{width: '10%'}
            = link_to "Delete".html_safe, user_path(user), method: :delete, class: 'btn btn-default btn-xs', data: {confirm: 'Are you sure you want to remove this service advisor?'}
.row.pA50
  .col-md-12.text-center
    = link_to 'Invite ' + t('users.roles.service_advisor'), new_user_invitation_path, class: 'btn btn-primary btn-lg'

app/views/users/show.html.haml
%h1 User Home

%p
  You are logged in.

app/views/users/technicians.html.haml
.row.mB20
  .col-xs-12
    = link_to 'Add Technician', new_technician_users_path, class: 'btn btn-primary btn-lg pull-right mB20'
= render 'users', users: @users
%br