config/routes.rb
# Route prefixes use a single letter to allow for vanity urls of two or more characters
Rails.application.routes.draw do
  if defined? Sidekiq
    require 'sidekiq/web'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web, at: '/admin/sidekiq/jobs', as: :sidekiq
    end
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin' if defined? RailsAdmin

  # Static pages
  match '/error' => 'pages#error', via: [:get, :post], as: 'error_page'
  get '/terms' => 'pages#terms', as: 'terms'
  get '/privacy' => 'pages#privacy', as: 'privacy'

  # OAuth
  oauth_prefix = Rails.application.config.auth.omniauth.path_prefix
  get "#{oauth_prefix}/:provider/callback" => 'users/oauth#create'
  get "#{oauth_prefix}/failure" => 'users/oauth#failure'
  get "#{oauth_prefix}/:provider" => 'users/oauth#passthru', as: 'provider_auth'
  get oauth_prefix => redirect("#{oauth_prefix}/login")

  # Devise
  devise_prefix = Rails.application.config.auth.devise.path_prefix

  # hack for blocking registration
  get "#{devise_prefix}/signup" => redirect('404')

  devise_for :users, path: devise_prefix,
             controllers: {registrations: 'users/registrations',
                           sessions: 'users/sessions',
                           passwords: 'users/passwords',
                           confirmations: 'users/confirmations',
                           unlocks: 'users/unlocks',
                           :invitations => 'users/invitations'},
             path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}

  devise_scope :user do
    get "#{devise_prefix}/after" => 'users/registrations#after_auth', as: 'user_root'
    root 'users/sessions#new'
  end

  get devise_prefix => redirect('/a/signup')

  # User
  resources :users, path: 'u', only: [:show, :index, :new, :edit, :update, :create, :destroy] do
    collection do
      get :login_as
      get :new_technician
      get :technicians
      get :service_advisors

      post :create_technician
    end

    member do
      post :login

      delete :destroy
    end

    resources :authentications, path: 'accounts'
  end

  resources :dealerships, except: :show
  resources :inventories, only: [:create]

  get '/home' => 'users#show', as: 'user_home'

  # Dummy preview pages for testing.
  get '/p/test' => 'pages#test', as: 'test'
  get '/p/email' => 'pages#email' if ENV['ALLOW_EMAIL_PREVIEW'].present?

  get 'robots.:format' => 'robots#index'

  resources :vehicle_report_cards, path: 'reports' do
    resources :next_maintenance_appointments
    resources :scheduled_maintenance_items
    resources :fluid_levels
    resources :wiper_blades
    resources :vehicle_components
    resources :tire_wear_indicates
    resources :brake_wear_indicates
    member do
      get :send_pdf
      get :email_pdf
    end
  end
end

app/models/vehicle_report_card.rb
class VehicleReportCard < ActiveRecord::Base
  include AASM

  aasm do
    state :to_be_reviewed, :initial => true
    state :reviewed
    state :sent_to_customer

    event :review do
      transitions :from => :to_be_reviewed, :to => :reviewed
    end

    event :send_to_customer do
      transitions :from => :reviewed, :to => :sent_to_customer
    end
  end

  acts_as_paranoid

  VIN_LENGTH = 17
  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  paginates_per 5

  belongs_to :user

  has_one :next_maintenance_appointment, dependent: :destroy, :inverse_of => :vehicle_report_card
  has_one :brake_wear_indicate, dependent: :destroy, :inverse_of => :vehicle_report_card
  has_one :tire_wear_indicate, dependent: :destroy, :inverse_of => :vehicle_report_card
  has_one :vehicle_component, dependent: :destroy, :inverse_of => :vehicle_report_card
  has_one :battery, dependent: :destroy, :inverse_of => :vehicle_report_card
  has_one :wiper_blade, dependent: :destroy, :inverse_of => :vehicle_report_card
  has_one :fluid_level, dependent: :destroy, :inverse_of => :vehicle_report_card
  has_one :scheduled_maintenance_item, dependent: :destroy, :inverse_of => :vehicle_report_card

  accepts_nested_attributes_for :next_maintenance_appointment, allow_destroy: true, update_only: true
  accepts_nested_attributes_for :brake_wear_indicate, allow_destroy: true, update_only: true
  accepts_nested_attributes_for :tire_wear_indicate, allow_destroy: true, update_only: true
  accepts_nested_attributes_for :vehicle_component, allow_destroy: true, update_only: true
  accepts_nested_attributes_for :battery, allow_destroy: true, update_only: true
  accepts_nested_attributes_for :wiper_blade, allow_destroy: true, update_only: true
  accepts_nested_attributes_for :fluid_level, allow_destroy: true, update_only: true
  accepts_nested_attributes_for :scheduled_maintenance_item, allow_destroy: true, update_only: true

  validates :vehicle_identification_number, presence: true
  validates :vehicle_identification_number, length: { is: VIN_LENGTH }
  validates :customer_email, allow_blank: true, format: {with: VALID_EMAIL_REGEX }
  validates :odometer, numericality: {greater_than: 0}, presence: true
  validates :user_id, presence: true

  before_validation :validate_odometer
  after_create :notify_service_advisor

  def validate_odometer
    comparision_time = new_record? ? Time.zone.now : self.created_at
    vehilcle_report_card_previous = VehicleReportCard.where(vehicle_identification_number: self.vehicle_identification_number).where("created_at < ?", comparision_time).order("created_at asc").last
    vehilcle_report_card_next = VehicleReportCard.where(vehicle_identification_number: self.vehicle_identification_number).where("created_at > ?", comparision_time).order("created_at asc").first

    if vehilcle_report_card_previous && (self.odometer.to_i < vehilcle_report_card_previous.odometer.to_i)
      self.errors.add(:odometer, "cannot be lesser than previous reports. Previous report has odometer been set at #{vehilcle_report_card_previous.odometer}.") && false
    elsif vehilcle_report_card_next && (self.odometer.to_i > vehilcle_report_card_next.odometer.to_i)
      self.errors.add(:odometer, "cannot be greater than next reports. Next report has odometer been set with #{vehilcle_report_card_next.odometer}.") && false
    else
      true
    end
  end

  def aasm_state_label_css_class
    if to_be_reviewed?
      'label-danger'
    elsif reviewed?
      'label-warning'
    elsif sent_to_customer?
      'label-success'
    else
      'label-default'
    end
  end

  def notify_service_advisor
    VehicleReportCardMailer.notify_service_advisor(self).deliver_now if user.technician? && service_advisor.try(:email).present?
  end

  def self.report_cards(user)
    where('user_id in (?)',(user.dealership.users).pluck(:id)).pluck(:id)
  end

  # Convert datetime from string to datetime object
  def self.set_date(card_date)
    DateTime.strptime(card_date, '%m/%d/%Y %H:%M %P').utc
  end

  def technician
    User.unscoped.find(technician_id) if technician_id.present?
  end

  def inventory_exists?
    inventories.count > 0
  end

  def inventories
    Inventory.where(vin: vehicle_identification_number)
  end

  def inventory
    inventories.first
  end

  def email_report(pdf)
    VehicleReportCardMailer.email_report_card(self, pdf, user.dealership).deliver_now
    send_to_customer! unless sent_to_customer?
  end

  def service_advisor
    User.where(id: service_advisor_id).first
  end
end

app/controllers/vehicle_report_cards_controller.rb
class VehicleReportCardsController < ApplicationController
  include ApplicationHelper
  layout "application-pdf", only: [:show]

  before_action :authenticate_user!
  load_and_authorize_resource

  before_action :set_instance_variables, only: [:create, :update, :new, :edit]
  before_action :set_report_card, only: [:edit, :update, :destroy, :download_pdf, :send_pdf, :email_pdf]
  before_action :mark_reviewed, only: :edit

  def index
    begin
      @vehicle_report_cards = VehicleReportCard.accessible_by(Ability.new current_user).joins(:user).includes(:user).order(params[:order].presence || 'vehicle_report_cards.created_at desc')
      @vehicle_report_cards = @vehicle_report_cards.where("users.last_name ILIKE '%#{params[:user]}%' or users.first_name ILIKE '%#{params[:user]}%' or users.username ILIKE '%#{params[:user]}%' or users.email ILIKE '%#{params[:user]}%'",) if params[:user].present?
      @vehicle_report_cards = @vehicle_report_cards.where("vehicle_report_cards.vehicle_identification_number ILIKE '%#{params[:vin]}%'") if params[:vin].present?

    rescue ArgumentError # as order is exposed. There might be cases where user might change the url
      @vehicle_report_cards = VehicleReportCard.none
    end
    @vehicle_report_cards = @vehicle_report_cards.page params[:page]
  end

  def new
    @vehicle_report_card = VehicleReportCard.new
    @vehicle_report_card.build_next_maintenance_appointment
    @vehicle_report_card.build_scheduled_maintenance_item
    @vehicle_report_card.build_fluid_level
    @vehicle_report_card.build_wiper_blade
    @vehicle_report_card.build_battery
    @vehicle_report_card.build_vehicle_component
    @vehicle_report_card.build_tire_wear_indicate
    @vehicle_report_card.build_brake_wear_indicate
  end

  def create
    @vehicle_report_card = VehicleReportCard.new(vehicle_report_card_params.merge(user_id: current_user.id))
    @vehicle_report_card.build_fluid_level if @vehicle_report_card.fluid_level.blank? #Hack
    respond_to do |format|
      if @vehicle_report_card.save
        format.html { redirect_to vehicle_report_cards_path, notice: 'New report created successfully.' }
        format.js
      else
        format.html { render 'new' }
        format.js
      end
    end
  end

  def edit
    @vehicle_report_card.build_fluid_level if @vehicle_report_card.fluid_level.blank?
  end

  def update
    respond_to do |format|
      if @vehicle_report_card.update_attributes(vehicle_report_card_params)
        format.html { redirect_to vehicle_report_cards_path, notice: 'Updated successfully.' }
        format.js { render 'send_pdf' } if request.format == 'text/javascript' && Rails.application.routes.recognize_path(request.referrer)[:action] == 'edit'
        format.js
      else
        format.html { render 'edit' }
        format.js
      end
    end
  end

  def destroy
    @vehicle_report_card.destroy
    respond_to do |format|
      format.html { redirect_to vehicle_report_cards_path, notice: 'Report successfully destroyed.' }
    end
  end

  def show
    @vehicle_report_card.build_fluid_level if @vehicle_report_card.fluid_level.blank?
    generate_pdf(@vehicle_report_card)
    # respond_to do |format|
    #   format.html
    # end
  end

  def send_pdf
    respond_to do |format|
      format.js
    end
  end

  def email_pdf
    pdf = render_to_string pdf: "test", template: "vehicle_report_cards/show.html.haml"
    @vehicle_report_card.email_report(pdf)

    flash[:notice] = "Email has been sent successfully."
    redirect_to vehicle_report_cards_path
  end

  private

  def mark_reviewed
    @vehicle_report_card.review! if current_user.service_advisor? && @vehicle_report_card.to_be_reviewed?
  end

  def vehicle_report_card_params
    params.require(:vehicle_report_card).permit(:user_id, :report_card_date, :ro, :name, :email, :year, :make, :model, :vehicle_identification_number, :plate, :odometer, :owner_guide, :open_field_service_actions, :reset_oil_life_monitor, :service_advisor_id, :technician_id, :comments, :customer_declined_ford_maintanence, :exterior_body_note, :extended_service_plan, :owner_advantage_reward, :service_balance, :customer_email,
                                                :next_maintenance_appointment_attributes => [:id, :service_description, :appointment_date, :price, :appointment_time],
                                                :scheduled_maintenance_item_attributes => [:id, :the_works, :the_works_serviced, :oil_changes, :oil_changes_serviced, :tire_rotation, :tire_rotation_serviced, :multipoint_inspection, :multipoint_inspection_serviced, :fuel_filter, :fuel_filter_serviced, :engine_air_filter, :engine_air_filter_serviced, :engine_coolant_filter, :engine_coolant_filter_serviced, :transmission_fluid_filter, :transmission_fluid_filter_serviced, :cabin_air_filter, :cabin_air_filter_serviced, :spark_plugs, :spark_plugs_serviced, :km_scheduled_maintenance],
                                                :fluid_level_attributes => [:id, :fluid_levels_serviced, :engine_oil, :brake_reservoir, :power_steering, :window_washer, :transmission, :coolent_recovery_reservoir],
                                                :wiper_blade_attributes => [:id, :wiper_test_performed, :wiper_blade_legend, :wiper_blade_serviced],
                                                :battery_attributes => [:id, :battery_condition_legend, :factory_spec_amps, :actual_amps, :battery_serviced],
                                                :vehicle_component_attributes => [:id, :light_legend, :light_serviced, :windshield_legend, :windshield_serviced, :hvac_system_hoses_legend, :hvac_system_hoses_serviced, :engine_cooling_legend, :engine_cooling_serviced, :accessory_drive_belts_legend, :accessory_drive_belts_serviced, :brake_system_legend, :brake_system_serviced, :suspension_legend, :suspension_serviced, :steering_legend, :steering_serviced, :exhaust_system_legend, :exhaust_system_serviced, :clutch_legend, :clutch_legend_serviced, :constant_velocity_legend, :constant_velocity_serviced, :drive_shaft_legend, :drive_shaft_serviced],
                                                :tire_wear_indicate_attributes => [:id, :alignment_check_needed, :wheel_balance_needed, :left_front_tread_depth, :left_front_tread_depth_legend, :left_front_tread_depth_serviced, :left_front_pattern_legend, :left_front_pattern_serviced, :left_front_psi_legend, :left_front_psi_serviced, :left_front_tire_age, :left_rear_tread_depth, :left_rear_tread_depth_legend, :left_rear_tread_depth_serviced, :left_rear_pattern_legend, :left_rear_pattern_serviced, :left_rear_psi_legend, :left_rear_psi_serviced, :left_rear_tire_age, :right_front_tread_depth, :right_front_tread_depth_legend, :right_front_tread_depth_serviced, :right_front_pattern_legend, :right_front_pattern_serviced, :right_front_psi_legend, :right_front_psi_serviced, :right_front_tire_age, :right_rear_tread_depth, :right_rear_tread_depth_legend, :right_rear_tread_depth_serviced, :right_rear_pattern_legend, :right_rear_pattern_serviced, :right_rear_psi_legend, :right_rear_psi_serviced, :right_rear_tire_age, :spare_tire_age, :spare_tire_psi_legend, :spare_tire_serviced, :alignment_check_serviced, :wheel_balance_serviced],
                                                :brake_wear_indicate_attributes => [:id, :left_front_brake_lining, :left_front_legend, :left_front_serviced, :left_rear_brake_lining, :left_rear_legend, :left_rear_serviced, :right_front_brake_lining, :right_front_legend, :right_front_serviced, :right_rear_brake_lining, :right_rear_legend, :right_rear_serviced]
    )
  end

  def set_instance_variables
    @service_advisors = current_user.admin? ? User.service_advisor : current_user.dealership.users.service_advisors
    @technicians = current_user.admin? ? User.technician : current_user.dealership.users.technicians
  end

  def set_report_card
    @vehicle_report_card = VehicleReportCard.find(params[:id])
  end

end

app/helpers/vehicle_report_cards_helper.rb
module VehicleReportCardsHelper
  def check_box_block(f, column)
    content_tag :div, class: f.object.send(column) ? 'checked check-box-block' : 'check-box-block' do
      element = content_tag(:i, nil, {class: 'fa fa-check'})
      element += f.check_box(column)
    end
  end

  def legend column, f, except = []
    except ||= []
    div = content_tag :div, class: "btn-group", data: {toggle: "buttons"} do
      label = ""

      {g: {class: "btn-success"}, y: {class: 'btn-warning'}, r: {class: 'btn-danger'}}.each_pair do |key, options|
        checked = f.object.send(column) == key.to_s
        label += content_tag :label, data: {toggle: 'tooltip', title: t("legend.#{key}")}, class: legend_label_class(key, options, checked, except) do
          f.radio_button(column, key, checked: checked) + content_tag(:i, ' ', class: "fa fa-check #{checked ? '' : 'invisible'}")
        end
      end
      label.html_safe
    end
    div
  end

  def legend_label_class(key, options, checked, except = [])
    "btn btn-lg mR10 #{options[:class]} #{checked or @vehicle_report_card.new_record? ? "" : "backgroundGrey"}" + (except.include?(key.to_sym) ? ' vHidden' : '') + (checked ? ' active' : '')
  end
end

app/views/vehicle_report_cards/_email_from.html.haml
= form_for (@vehicle_report_card), html: { class: "form-horizontal", id: "email_report_card", data: {jquery_validate: true} }, remote: true do |f|
  .row
    .col-md-12
      .form-group
        = f.email_field :customer_email, placeholder: t('activerecord.attributes.vehicle_report_card.customer_email'), class: 'form-control', required: true
  .row
    .col-md-12
      .form-group
        %button.btn.btn-success{:id => "btn-report-card",:type => "submit"} Submit
        %a.btn.btn-default{id: 'btn-cancel'} Cancel

app/views/vehicle_report_cards/_form.html.haml
- if current_user.technician? && !@vehicle_report_card.to_be_reviewed?
  = alert_box context: 'danger' do
    Report has been already reviewed by service advisor. Updating the report has been disabled.
= form_for (@vehicle_report_card), html: { class: "form-horizontal", name: "report_card", data: {jquery_validate: true} } do |f|
  = render 'application/active_record_errors', object: @vehicle_report_card
  %section
    .row
      .col-md-6
        .form-group
          = f.text_field :vehicle_identification_number, minlength: VehicleReportCard::VIN_LENGTH, maxlength: VehicleReportCard::VIN_LENGTH, required: true, placeholder: t('activerecord.attributes.vehicle_report_card.vehicle_identification_number'), class: 'form-control input-lg'
        .form-group
          .input-group
            = f.number_field :odometer, placeholder: t('activerecord.attributes.vehicle_report_card.odometer'), class: 'form-control input-lg'
            %span.input-group-btn
              %button.btn.btn-default.btn-lg{:type => "button"} KM
        .form-group
          .input-group
            = f.text_field :report_card_date, placeholder: t('activerecord.attributes.vehicle_report_card.report_card_date'), class: 'form-control input-lg datetimepicker'
            %span.input-group-addon
              %i.fa.fa-calendar
        .form-group
          - if can?(:send_pdf, @vehicle_report_card) && can?(:email_pdf, @vehicle_report_card) && !@vehicle_report_card.new_record?
            .input-group
              = f.email_field :customer_email, placeholder: t('activerecord.attributes.vehicle_report_card.customer_email'), class: 'form-control input-lg'
              %span.input-group-btn
                = link_to 'SEND', send_pdf_vehicle_report_card_path(@vehicle_report_card), class: 'btn btn-default btn-lg btn-block pT20 pB20', id: 'send_pdf', remote: true, class: 'btn btn-default btn-lg'
          - else
            = f.email_field :customer_email, placeholder: t('activerecord.attributes.vehicle_report_card.customer_email'), class: 'form-control input-lg'
      .col-md-6
        #vin-dataone-info
          = render 'inventories/inventory', inventory: @vehicle_report_card.inventory
  %input{:id => "record_type", :type => "hidden", :value => @vehicle_report_card.new_record? ? "new" : "edit" }/
  %input{:id => "record_id", :type => "hidden", :value => @vehicle_report_card.id }/
  .row.service-button.pdf-page
    .col-md-6
      = f.fields_for :scheduled_maintenance_item do |_f|
        =  render 'scheduled_maintenance_items/form', f: _f
    .col-md-6
      = f.fields_for :fluid_level do |_f|
        =  render 'fluid_levels/form', f: _f
  .row.pdf-page
    .col-md-6
      = f.fields_for :wiper_blade do |_f|
        =  render 'wiper_blades/form', f: _f
    .col-md-6
      = f.fields_for :battery do |_f|
        =  render 'batteries/form', f: _f
  %section.component
    = f.fields_for :vehicle_component do |_f|
      =  render 'vechicle_components/form', f: _f
  %section.pdf-page
    = f.fields_for :tire_wear_indicate do |_f|
      =  render 'tire_wear_indicates/form', f: _f
  %section
    = f.fields_for :brake_wear_indicate do |_f|
      =  render 'brake_wear_indicates/form', f: _f
  %section.component
    = f.fields_for :next_maintenance_appointment do |_f|
      =  render 'next_maintenance_appointments/form', f: _f
  .form-group
    = f.select :service_advisor_id, @service_advisors.collect {|p| [ p.display_name, p.id ] }, {prompt: "Please Select #{t('activerecord.attributes.vehicle_report_card.service_advisor_id')}"}, class: 'form-control input-lg'
  .form-group
    - selected_technician_id = @vehicle_report_card.technician_id || (current_user.technician? ? current_user.id : nil)
    = f.select :technician_id, @technicians.collect {|p| [ p.display_name, p.id ] }, {selected: selected_technician_id,  prompt: "Please Select #{t('activerecord.attributes.vehicle_report_card.technician_id')}"}, class: 'form-control input-lg'
  .form-group
    = f.text_field :comments,placeholder: t('activerecord.attributes.vehicle_report_card.comments'), class: 'form-control input-lg'
  .row.pB50#pdf_friendly
    .col-md-4.col-sm-4.col-xs-4
      - if current_user.technician? && (@vehicle_report_card.to_be_reviewed? or @vehicle_report_card.new_record?)
        %button.btn.btn-warning.btn-lg.btn-block.pT20.pB20{:id => "btn-report-card",:type => "submit"} Submit
    .col-md-4.col-sm-4.col-xs-4
      - if can?(:send_pdf, @vehicle_report_card) && can?(:email_pdf, @vehicle_report_card)
        = link_to 'E-mail PDF', send_pdf_vehicle_report_card_path(@vehicle_report_card), class: 'btn btn-default btn-lg btn-block pT20 pB20', id: 'send_pdf', remote: true
    .col-md-4.col-sm-4.col-xs-4
      = link_to 'Cancel', root_path, class: 'btn btn-default btn-lg btn-block pT20 pB20'

app/views/vehicle_report_cards/create.js.erb
<% if @vehicle_report_card.save %>
  $('form[name="report_card"]').attr('action', '/reports/<%= @vehicle_report_card.id %>');
  $('form[name="report_card"]').attr('id','edit_vehicle_report_card_<%= @vehicle_report_card.id %>');

  $('#record_type').val("edit")
  $('#record_id').val('<%= @vehicle_report_card.id %>')

  $('<input>').attr({
      type: 'hidden',
      value: 'patch',
      name: '_method'
  }).appendTo('form[name="report_card"]');

<% elsif @vehicle_report_card.errors.any? %>

  <% @vehicle_report_card.errors.full_messages.each do |message| %>
    var n = noty({
                    layout: 'topRight',
                    type: 'error',
                    text: '<%= message %>',
                    timeout: 5000
                });
  <% end %>

<% end %>

app/views/vehicle_report_cards/edit.html.haml
.row
  .col-md-12.col-sm-12
    = render 'form'

app/views/vehicle_report_cards/index.html.haml
- if can? :create, VehicleReportCard
  .row.mB20
    .col-md-12
      = link_to 'New Report', new_vehicle_report_card_path, class: 'btn btn-primary btn-lg pull-right'
- if @vehicle_report_cards.present?
  = panel do
    .panel-heading
      %strong Search
    .panel-body
      .row
        .col-md-12
          = form_tag(vehicle_report_cards_path, method: :get, class: 'form-inline') do
            .form-group
              %label{:for => "user"} User:
              = text_field_tag :user, params[:user], class: 'form-control', placeholder: 'Name / E-mail / Username'
            .form-group
              %label{:for => "vin"}
                #{t('activerecord.attributes.vehicle_report_card.vehicle_identification_number')}:
              = text_field_tag :vin, params[:vin], class: 'form-control', placeholder: 'eg: 1FTRF02W24KXXXXXX'
            %button.btn.btn-default{:type => "submit"}
              %i.fa.fa-search
              Search

  .table-responsive
    %table.table.table-striped.table-hover.table-bordered
      %thead
        %tr
          %th{width: '20%'}
            = link_to vehicle_report_cards_path({order: toggle_order(:vehicle_identification_number)}.merge(vin: params[:vin], user: params[:user])) do
              = t('activerecord.attributes.vehicle_report_card.vehicle_identification_number')
              %i.fa.fa-sort
          %th{width: '20%'}
            = link_to vehicle_report_cards_path({order: toggle_order(:report_card_date)}.merge(vin: params[:vin], user: params[:user])) do
              = t('activerecord.attributes.vehicle_report_card.report_card_date')
              %i.fa.fa-sort
          %th{width: '20%'}
            Status
          %th{width: '30%'}
            User
          %th{width: '10%'}
      %tbody
        - @vehicle_report_cards.each do |vehicle_report_card|
          %tr
            %td= link_to vehicle_report_card.vehicle_identification_number, edit_vehicle_report_card_path(vehicle_report_card)
            %td= vehicle_report_card.report_card_date.present? ? l(vehicle_report_card.report_card_date, format: :short) : '-'
            %td
              %span{class: "label #{vehicle_report_card.aasm_state_label_css_class}"}
                = vehicle_report_card.aasm_state.humanize
            %td= vehicle_report_card.user.name_or_email_or_username
            %td
              - if can? :destroy, @vehicle_report_card
                = link_to vehicle_report_card, class: 'btn btn-default btn-xs mR5', method: :delete, data: {confirm: 'Are you sure?', title: 'Delete', toggle: 'tooltip'}  do
                  %i.fa.fa-trash
              &nbsp;
              = link_to vehicle_report_card_path(vehicle_report_card), class: 'btn btn-default btn-xs mR5', data: {toggle: 'tooltip', title: 'Download PDF'} do
                %i.fa.fa-file-pdf-o
- else
  .row.pA50
    .col-md-12.text-center.mT50
      Nothing to display.
.pagination
  = paginate @vehicle_report_cards

app/views/vehicle_report_cards/new.html.haml
.row
  .col-md-12.col-sm-12
    = render 'form'

app/views/vehicle_report_cards/send_pdf.js.erb
<% if @vehicle_report_card.customer_email.present? %>
    $(".modal-body").empty().append("<p>Are you sure you want to mail PDF to <b><%= @vehicle_report_card.customer_email %></b> ? </p>");
    $(".modal-body").append("<p>If you want to change Email ID, Please click here, <a id='edit_email' remote='true'>Edit</a></p>");
    $(".modal-body").append("<div id='email-div'></div>");
    $(".modal-footer").empty().append("<a href='/reports/<%= @vehicle_report_card.id %>/email_pdf' class='btn btn-primary'>Email</a>");
    $(".modal-footer").append("<button class='btn btn-default' data-dismiss='modal' type='button'>Close</button>");
<% else %>
    <%- if can? :update, @vehicle_report_card%>
      $(".modal-body").empty().append("<p>Customer Email ID is not yet added. Please click here, <a id='edit_email'>Edit</a></p>");
    <% else %>
      $(".modal-body").empty().append("<p>Customer Email ID is not yet added by technician.</p>");
    <% end %>
    $(".modal-body").append("<div id='email-div'></div>");
    $(".modal-footer").empty().append("<button class='btn btn-default' data-dismiss='modal' type='button'>Close</button>");
<% end %>

$("#reportModal").modal("show");

$('#edit_email').on("click",function(){
    $("#email-div").empty().append("<%= j("#{render :partial => 'email_from'}").html_safe %>");
    $("#email-div").show();
});

app/views/vehicle_report_cards/update.js.erb
<% if @vehicle_report_card.errors.any? %>
  $('#vin-dataone-info').fadeOut("slow");
  <% @vehicle_report_card.errors.full_messages.each do |message| %>
    var n = noty({
                    layout: 'topRight',
                    type: 'error',
                    text: '<%= message %>',
                    timeout: 5000
                });
  <% end %>
<% end %>